### ISSUE TITLE
update-branch: make `--commands` root-relative

### ISSUE THREAD

**Issue by mathiasbynens** [alrra/travis-scripts#21] opened 2016-03-14 23:48 UTC
Make the `--commands` argument to `update-branch` relative to the repository’s root directory rather than to the `update-branch` path (which may change between versions).

Example where I had expected this behavior and it caused the build to fail: https://travis-ci.org/tibiamaps/tibia-map-data/builds/116006101#L1387 Matching `.travis.yml` config: https://github.com/tibiamaps/tibia-map-data/blob/f70d9a2b92aae2d9e430941a4aef73534242ac36/.travis.yml#L12-L13, i.e.:

```yaml
after_success:
  - "./scripts/travis/auto-deploy.sh"
```

Which includes https://github.com/tibiamaps/tibia-map-data/blob/f70d9a2b92aae2d9e430941a4aef73534242ac36/scripts/travis/auto-deploy.sh#L27:

```sh
$(npm bin)/update-branch --commands './travis/scripts/build.sh' […]
```

This could be as simple as running `cd "${TRAVIS_BUILD_DIR}";` before evaluating the `--commands`.

**Comment by mathiasbynens** [comment] 2016-04-05 19:26
FWIW, @alrra suggested to work around this issue by using `npm run build` which always runs relative to the root of the repository (since that’s where the `package.json` file is located). This is good enough for me, since I was using npm for this particular project anyway.

Still, this change would make sense IMHO, and could help other, non-npm projects.

**Comment by alrra** [comment] 2016-04-18 21:42
@mathiasbynens Thanks for opening this issue, and sorry for the delay on this!

--

The scripts execute the commands relative to the current path.

In the case you [pointed out](https://github.com/tibiamaps/tibia-map-data/blob/f70d9a2b92aae2d9e430941a4aef73534242ac36/scripts/travis/auto-deploy.sh#L27), because of [how that `auto-deploy.sh` script is called](https://github.com/tibiamaps/tibia-map-data/blob/f70d9a2b92aae2d9e430941a4aef73534242ac36/.travis.yml#L12-L13), the current path where `update-branch` is executed is actually the repository’s root directory (you can add a `pwd` in `auto-deploy.sh` to see). So, in order for things to work, you would have needed:  `--commands './scripts/travis/scripts/build.sh'`. 

--

I'm going to close this as I think making the commands relative to the repository’s root directory is very limiting and may not be the expected behavior for some.

**Closed by alrra** 2016-04-18 21:42 UTC

**Comment by mathiasbynens** [comment] 2016-04-19 05:43
Fair enough!
